# Generated by Django 2.2.28 on 2023-01-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20230120_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slugs',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
