# Generated by Django 2.2.28 on 2023-01-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slugs',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
